### PR TITLE
Fix typos and add a link

### PR DESCRIPTION
**Pull request by kmiya**
## Types of PR

- [X] Bugfix

## Description

Fix typos and add a link to the description of the "TierIV Scenario Format Version 2.0".

## How to review this PR.

Please check the sentence.

### CODE REVIEW

**Comment by kmiya** [comment]
@Igata-ctrl I think `setp` in line 22 would be a typo. How should I fix that?

**Review by Igata-ctrl — APPROVED** [review]
Miyahra-san,

Thank you for pointing out the typos and the missing link. All stand corrected.

**Comment by kmiya** [comment]
@Igata-ctrl Oops, `setp` still remains. How should I fix that?

**Comment by Igata-ctrl** [comment]
@kmiya Sorry, I'll include it in my next PR.

**Comment by kmiya** [comment]
@Igata-ctrl I see. Thank you!

**Pull request merged**
