### PR TITLE
Non-hardcoded map path

### PR DESCRIPTION
**Pull request by piotr-zyskowski-rai**
## Types of PR

- [ ] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue
https://tier4.atlassian.net/browse/AJD-239

## Description
This PR contains kashiwanoha_map package used to test modified autoware_auto.launch.py file

### CODE REVIEW

**Comment by piotr-zyskowski-rai** [comment]
I'm sorry. I choose wrong destination repository

**Comment by piotr-zyskowski-rai** [comment]
After additional tests I reopened this pull request for duscussion

**Comment by yamacir-kit** [comment]
@piotr-zyskowski-rai 

> There is also code that is needed to run autoware.auto base version instead of ArchitectureProposal. This part is for testing and will be removed in final version.

When it comes to the final version, please remove the WIP from the title and mention me!

**Comment by piotr-zyskowski-rai** [comment]
> @piotr-zyskowski-rai
> 
> > There is also code that is needed to run autoware.auto base version instead of ArchitectureProposal. This part is for testing and will be removed in final version.
> 
> When it comes to the final version, please remove the WIP from the title and mention me!

@yamacir-kit I wasn't very clear with what I wrote and I think it lead to misunderstanding. I'm sorry. 

I have prepared this PR in a way to be the most comfortable to test this solution on your side. Because [changes in launch file](https://gitlab.com/robotecai-public/AutowareAuto/-/merge_requests/1) are related to non-ArchitectureProposal version of autoware.auto, in this PR there are changes that enable excpected version for validation on your side:
```
test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
external/concealer/include/concealer/autoware_def.hpp
```
Other files are final from my perspective.

Please let me know if the final changes meet your requirements.

**Comment by yamacir-kit** [comment]
@piotr-zyskowski-rai 

Using this PR, I confirmed that https://gitlab.com/robotecai-public/AutowareAuto/-/merge_requests/1/diffs works.

We also tested if the YAML file needed for AA is not in map_path.
The result was a crash, but this is acceptable because the launch file shouldn't be responsible for checking the files that should be in map_path (I think the concealer should be).
At present, it is enough to be able to output as an error message what files are missing.

**Comment by piotr-zyskowski-rai** [comment]
@yamacir-kit 

This branch is now ready to be reviewed and hopefully merged. I removed changes for testing, which was moved to `pzyskowski/AutowareAuto_integration` branch, which is now checked out in [launch file changes](https://gitlab.com/robotecai-public/AutowareAuto/-/merge_requests/1)

**Comment by yamacir-kit** [comment]
(This PR doesn't introduce any new features, so I removed the feature label)

**Review by yamacir-kit — APPROVED** [review]

**Pull request merged**
