### PR TITLE
Add a node to convert from DiagnosticArray to ParameterDeclaration

### PR DESCRIPTION
**Pull request by kyoichi-sugahara**
## Types of PR

- [x] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue
remake of this PR
Needed to integrate the planner evaluation metrics (https://tier4.atlassian.net/browse/T4PB-10536) with the scenario runner.

## Description

Add the `diagnostic_converter` package which contains a node to convert `diagnostic_msgs::msg::DiagnosticArray` messages into `openscenario_msgs::msg::ParameterDeclaration`.

Also update the launch file to run the converter and the planning evaluator that publishes `DiagnosticArray` messages.

## How to review this PR.

Checkout branch [feature/integ-planning-evaluator](https://github.com/tier4/AutonomousDrivingScenarios/tree/feature/integ-planning-evaluator) on the following repositories (in addition to scenario_simulator_v2).

AutonomousDrivingScenarios: adds a test scenario which uses a UserDefinedCondition based on a metric published by the planning evaluator.
Run command ./run_scenario.sh metric_test.yaml inside AutonomousDrivingScenarios/scripts.
(Make sure you source install/setup.sh after building autoware.universe).

The test scenario metric_test.yaml listens to `/diagnostic/planning_evaluator/metrics_stability_mean` and the scenario fails if the corresponding value is greater than 0.2. The original data is published on topic `/planning_evaluator/metrics_stability_mean` as a DiagnosticArray message.

### CODE REVIEW

**Comment by kyoichi-sugahara** [comment]
https://user-images.githubusercontent.com/32741405/186298516-431cb401-a4a7-435a-adcb-aed1fbf0b17b.mp4

**Comment by kyoichi-sugahara** [comment]
@hakuturu583 @yamacir-kit 
ローカル上ではシナリオ動かせるのですが、こちらfailしてしまう要因わかりますでしょうか？
https://github.com/tier4/scenario_simulator_v2/runs/7985979824?check_suite_focus=true

**Comment by kyoichi-sugahara** [comment]
We are considering taking a different approach to integrate with the planning_evaluator, so change this PR to draft.

**Comment by hakuturu583** [comment]
@kyoichi-sugahara Please update repos file.

**Comment by kyoichi-sugahara** [comment]
@hakuturu583 
We are planning to separate `openscenario_msgs` and create a separate repository and proceed to integrate planning_evaluator with the policy of creating a converter node for the messages in autoware side.

**Comment by yamacir-kit** [comment]
**This pull request is closed because the implementation plan has changed to include `diagnostic_converter` in the Autoware repository instead of this repository.**

**Pull request closed without merging**
