### PR TITLE
Improve occupancy grid performance

### PR DESCRIPTION
**Pull request by shouth**
## Types of PR

- [ ] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

### CODE REVIEW

**Comment by shouth** [comment]
現段階でボトルネックになっている部分は `generate` 関数内部の以下の三箇所

1. 5~7msぐらい https://github.com/tier4/scenario_simulator_v2/blob/3f4cba31f0fde441660b4fed1c64099a08fd6603/simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_generator.cpp#L28

2. 2~3msぐらい
https://github.com/tier4/scenario_simulator_v2/blob/3f4cba31f0fde441660b4fed1c64099a08fd6603/simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_generator.cpp#L29-L31

3. 2~3msぐらい
https://github.com/tier4/scenario_simulator_v2/blob/3f4cba31f0fde441660b4fed1c64099a08fd6603/simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_generator.cpp#L36

**Comment by shouth** [comment]
`Grid` のコンストラクタはメンバ関数 `getAllCells` を呼び出しており，この関数が遅い．

https://github.com/tier4/scenario_simulator_v2/blob/3f4cba31f0fde441660b4fed1c64099a08fd6603/simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/grid.cpp#L98-L113

そこで `GridCell` 及び `getAllCells` を次のように書き換えたところ2~3msにまでパフォーマンスが改善した．

```diff
--- a/simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/grid.hpp
+++ b/simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/grid.hpp
@@ -29,15 +29,17 @@ namespace simple_sensor_simulator
 class Grid
 {
 public:
+  Grid() = default;
+
   Grid(
     const geometry_msgs::msg::Pose & origin, double resolution, size_t height, size_t width,
     int8_t occupied_cost = 100, int8_t invisible_cost = 50);
-  const double resolution;
-  const size_t height;
-  const size_t width;
-  const geometry_msgs::msg::Pose origin;
-  const int8_t occupied_cost;
-  const int8_t invisible_cost;
+  double resolution;
+  size_t height;
+  size_t width;
+  geometry_msgs::msg::Pose origin;
+  int8_t occupied_cost;
+  int8_t invisible_cost;
   void addPrimitive(const std::unique_ptr<primitives::Primitive> & primitive);
   std::vector<int8_t> getData();
```

```diff
--- a/simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/grid.cpp
+++ b/simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/grid.cpp
@@ -97,7 +97,7 @@ math::geometry::LineSegment Grid::transformToPixel(const math::geometry::LineSeg
 
 std::vector<GridCell> Grid::getAllCells() const
 {
-  std::vector<GridCell> ret;
+  auto ret = std::vector<GridCell>(height * width);
   for (size_t x_index = 0; x_index < height; x_index++) {
     for (size_t y_index = 0; y_index < width; y_index++) {
       geometry_msgs::msg::Pose cell_origin;
@@ -105,8 +105,7 @@ std::vector<GridCell> Grid::getAllCells() const
       cell_origin.position.y = origin.position.y + (y_index - 0.5 * width) * resolution;
       cell_origin.position.z = origin.position.z;
       cell_origin.orientation = origin.orientation;
-      ret.emplace_back(
-        GridCell(cell_origin, resolution, width * y_index + x_index, y_index, x_index));
+      ret[width * x_index + y_index] = { cell_origin, resolution, width * x_index + y_index, y_index, x_index;
     }
   }
   return ret;
```

**Comment by shouth** [comment]
`Grid` は `OccupancyGridGenerator` 内部でのみ利用されていて，なおかつコンストラクタの4個の引数のうち `configuration` 由来の3個の引数は必ず同じになるので，`Grid` を `OccupancyGridGenerator` のメンバ変数として持たせてしまった上で，メモリの再確保を避けつつ値を更新する仕組みができるとさらなる高速化が見込めそう

**Comment by shouth** [comment]
Currently, `Grid` maintains its cells as [AoS](https://en.wikipedia.org/wiki/AoS_and_SoA).

https://github.com/tier4/scenario_simulator_v2/blob/3f4cba31f0fde441660b4fed1c64099a08fd6603/simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/grid.hpp#L45

While we heavily update `data_` of adjacent `GridCell`s, other member variables of `GridCell` are constant. So treating `data_` by SoA may improve performance.

**Comment by shouth** [comment]
Applied this https://github.com/tier4/scenario_simulator_v2/pull/849#issuecomment-1204860041. Now we can avoid `Grid` construction time and `OccupancyGridGenerator` runs 2x faster.

**Review by hakuturu583 — APPROVED** [review]
LGTM

**Pull request merged**
