### PR TITLE
Random test runner AWSIM support

### PR DESCRIPTION
**Pull request by piotr-zyskowski-rai**
# Description

## Abstract

This PR adds:
- random_test_runner AWSIM support
  - enabled ego spawning when working with Unity simulator
  - changed simulator_type for working with AWSIM from unity to awsim
  - added docs on how to run random_test_runner with AWSIM
- test timeout configuration support with docs update

This PR is based on https://github.com/tier4/scenario_simulator_v2/pull/1143 to include the new documentation structure. PR #1143  should be merged before this one.

## Background

Currently random_test_runner  only supports simple_sensor_simulator, this feature enable support AWSIM.

## Details

N/A

## References

https://tier4.atlassian.net/browse/RJD-708

# Destructive Changes

N/A

# Known Limitations

N/A

### CODE REVIEW

**Review by hakuturu583 — CHANGES_REQUESTED** [review]
Is this pull request really only dependent on #1152?
It looks like it also depends on #1143 as far as I can tell from the Diff.
Reqeust change to prevent merge by mistake.

**Comment by piotr-zyskowski-rai** [comment]
> Is this pull request really only dependent on #1152? It looks like it also depends on #1143 as far as I can tell from the Diff. Reqeust change to prevent merge by mistake.

@hakuturu583 Yes, you are correct. I linked the wrong PR. I updated the description accordingly. 
I will solve the conflicts today too.

**Comment by hakuturu583** [comment]
#1143 was merged.
Please follow master branch in upstream repository and reduce diff for review.

**Comment by pawellech1** [comment]
@hakuturu583 I merged master branch. The PR is now ready for review.

**Comment by pawellech1** [comment]
@hakuturu583 Please let me know if there is anything more that should be done regarding this PR?

**Comment by hakuturu583** [comment]
@piotr-zyskowski-rai Could you follow upstream?

**Review by hakuturu583 — APPROVED** [review]

**Pull request merged**
