### PR TITLE
Remove use sim time

### PR DESCRIPTION
**Pull request by wep21**
Signed-off-by: wep21 <border_goldenmarket@yahoo.co.jp>

## Types of PR

- [ ] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

## Description

Remove unused env variable for use sim time

## Others
Related PR https://github.com/tier4/autoware.iv/pull/1260

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@yamacir-kit これらをuse_sim_time=trueで使うことってありますか？

**Comment by yamacir-kit** [comment]
@kenji-miyake 
Yes.
We will need it for future time-accelerated / decelerated simulations for Autoware.
However, Autoware doesn't currently support time acceleration, and it's undecided whether it will support it in the future, so it's safe to assume that use_sim_time = true will not happen in the near future.

**Comment by kenji-miyake** [comment]
@yamacir-kit Then, what is the top-level launch file? We should add `set_parameter` in the file.
Please see https://github.com/tier4/autoware_launcher/pull/198 for the reason.

**Comment by yamacir-kit** [comment]
@kenji-miyake 
Currently, launch files other than scenario_test_runner.launch.py located under `test_runner/scenario_test_runner/launch` are in the deprecated state.

In order to wipe out these hard-copied launch files, there is a PR that makes Autoware's launch compatible with PSim v2 (
https://github.com/tier4/autoware_launcher/pull/197).

Therefore, if planning_simulator.launch.xml of autoware_launch supports set_parameter, there is no problem to delete use_sim_time with this PR.

**Comment by kenji-miyake** [comment]
@yamacir-kit So, do you mean that we should add an arg for `use_sim_time` to `planning_simulator.launch.xml`?
Is it okay for you to set the default parameter to `false`?

**Comment by yamacir-kit** [comment]
@kenji-miyake yes.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
