### PR TITLE
Feature/sync release note

### PR DESCRIPTION
**Pull request by HansRobo**
## Types of PR

- [x] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Description

Add workflow to sync ReleaseNotes to Confluence

### CODE REVIEW

**Comment by hakuturu583** [comment]
Please also add a workflow dispatch trigger for this action for the manual hook.
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

**Review by hakuturu583 — CHANGES_REQUESTED** [review]
Please also add a workflow dispatch trigger for this action for the manual hook.
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

**Comment by HansRobo** [comment]
Thank you for your review!
I added `workflow_dispatch` trigger

**Review by hakuturu583 — APPROVED** [review]
LGTM

**Pull request merged**
