### PR TITLE
AJD-254 - Random test runner

### PR DESCRIPTION
**Pull request by piotr-zyskowski-rai**
## Types of PR

- [X] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Link to the issue
https://tier4.atlassian.net/browse/AJD-254

## Description
Random test runner allows running randomly generated scenarios to test autoware autonomy implementation.

## How to review this PR.
- [ ] Review code
- [ ] Follow included instruction:
https://github.com/RobotecAI/scenario_simulator_v2/blob/74c4b15f7d94f21689aadffb92f03e10e36b892c/test_runner/random_test_runner/Readme.md

## Others
n/a

### CODE REVIEW

**Review by hakuturu583 — CHANGES_REQUESTED** [review]
Please add your new package to the depends of scenario_simulator_v2 package.
https://github.com/tier4/scenario_simulator_v2/blob/master/scenario_simulator_v2/package.xml

**Comment by hakuturu583** [comment]
And, please modify CI workflow.
https://github.com/tier4/scenario_simulator_v2/blob/66239dda22feb6cd6e8cd775cccbc1f0f401b27e/.github/workflows/BuildIsolate.yaml#L20

**Comment by hakuturu583** [comment]
Where is the scenario_simulator_launch package?

**Comment by piotr-zyskowski-rai** [comment]
@hakuturu583 

> Where is the scenario_simulator_launch package?

It's a part of Autoware.Auto repository

> And, please modify CI workflow.

I did not modify it before. Should I simply add `random_test_runer` package to the list?

**Comment by piotr-zyskowski-rai** [comment]
@hakuturu583 I have fulfilled your review comments. Please let me know if they are correctly applied

**Review by hakuturu583 — APPROVED** [review]

**Pull request merged**
