### PR TITLE
Update of Random Test Runner documentation

### PR DESCRIPTION
**Pull request by pawellech1**
## Types of PR

- [ ] New Features
- [X] Upgrade of existing features
- [ ] Bugfix

## Link to the issue
https://tier4.atlassian.net/browse/RJD-707

## Description
Upgrade of random test runner documentation. Includes also related update of random test runner launch file.

### CODE REVIEW

**Comment by hakuturu583** [comment]
When I followed the procedure, an exception was thrown.
Has this document been tested with the latest version?

```
[random_test_runner-1] [WARN] [1703139455.219185985] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[random_test_runner-1] terminate called after throwing an instance of 'common::scenario_simulator_exception::SemanticError'
[random_test_runner-1]   what():  Unexpected architecture_type "awf/auto" given for V2I traffic lights simulation.
```

**Review by hakuturu583 — CHANGES_REQUESTED** [review]
When I followed the procedure, an exception was thrown.
Has this document been tested with the latest version?

**Comment by pawellech1** [comment]
@hakuturu583 I rebased on the current master branch just now and I could not reproduce the issue following the procedure from "How to run section". Could you please confirm that after the build you used `ros2 launch random_test_runner random_test.launch.py` command to run the runner with no additional launch arguments? Otherwise could you please specify what other arguments were used?

**Comment by pawellech1** [comment]
@hakuturu583 I updated the PR because the random_test_runner executable name has changed meantime.

But this was not the root of your issue. The exception you are linking states that the `awf/auto` architecture was used. This architecture is not used in the launch file from this PR and it is the architecture name which is the default on master. Could you please confirm that you have the `random-test-runner-docs-update` branch from https://github.com/RobotecAI/scenario_simulator_v2 fork checkout when this issue occurs?

**Comment by hakuturu583** [comment]
> Could you please confirm that after the build you used ros2 launch random_test_runner random_test.launch.py

I ran the command again as described in the documentation instructions, but the error log at my end did not change.

> But this was not the root of your issue. The exception you are linking states that the awf/auto architecture was used. This architecture is not used in the launch file from this PR and it is the architecture name which is the default on master.

Yes, I recognized.

**Comment by hakuturu583** [comment]
@HansRobo  I remember that you were in charge of V2I related issues, do you have any idea what the error is?

```
what():  Unexpected architecture_type "awf/auto" given for V2I traffic lights simulation.
```

**Comment by hakuturu583** [comment]
Thanks.
I found that the scenario_simulator_v2 package in my local environment was master branch.

**Review by hakuturu583 — APPROVED** [review]

**Pull request merged**
