### PR TITLE
Feature/unit tests/entity base

### PR DESCRIPTION
**Pull request by robomic**
# Description

## Abstract

This PR contains unit tests for `EntityBase`, which is a part of traffic_simulator package.

## Details

A mock implementation `DummyEntity`, contained in `dummy_entity.hpp`, was created to test `EntityBase` abstract class.
Repetitive functions used to instantiate objects in tests are included in `entity_helper_functions.hpp`.
All tests are included in `test_entity_base.cpp` file.
List of tests included in this PR:

1. appendDebugMarker
2. asFieldOperatorApplication
3. get2DPolygon
4. startNpcLogic
5. activateOutOfRangeJob_speed
6. activateOutOfRangeJob_acceleration
7. activateOutOfRangeJob_jerk
8. onUpdate
9. onPostUpdate
10. resetDynamicConstraints
11. requestLaneChange_absoluteTarget
12. requestLaneChange_relativeTarget
13. requestLaneChange_relativeTargetLaneletPose
14. requestLaneChange_relativeTargetnName
15. requestLaneChange_relativeTargetInvalid
16. setDynamicConstraints
17. setOtherStatus
18. setStatus
19. requestFollowTrajectory
20. requestWalkStraight
21. updateStandStillDuration_startedMoving
22. updateStandStillDuration_notStarted
23. updateTraveledDistance_startedMoving
24. updateTraveledDistance_notStarted
25. stopAtCurrentPosition
26. getLaneletPose_notOnRoadAndCrosswalkPedestrian
27. getLaneletPose_onRoadAndCrosswalkPedestrian
28. getLaneletPose_onCrosswalkNotOnRoadPedestrian
29. getLaneletPose_notOnRoadAndCrosswalkNotPedestrian
30. getLaneletPose_onRoadAndCrosswalkNotPedestrian
31. getLaneletPose_onCrosswalkNotOnRoadNotPedestrian
32. getMapPoseFromRelativePose_relative

## References
Jira ticket: [internal link](https://tier4.atlassian.net/browse/RJD-1048)

# Destructive Changes

There are no destructive changes.

### CODE REVIEW

**Review by hakuturu583 — CHANGES_REQUESTED** [review]
Why are you creating an Entity called DummyEntity that is only used for testing?
This is not a test of the EntityBase class.
If you want to test the EntityBase class, please write tests directly against the public member functions of the EntityBase class.

**Comment by hakuturu583** [comment]
I understand, but the DummyEntity class is not used inside the traffic_simulator and writing a unit test against it would not be a worthwhile test.

Please use VehicleEntity/PedestrianEntity/MiscObjectEntity etc. which are actually used inside traffic_simulator for your tests.

**Comment by hakuturu583** [comment]
I recommend that you re-create the pull request because it will be almost entirely rewritten.

**Comment by hakuturu583** [comment]
If you create an Entity for testing and test it, it cannot be a valid test.
I cannot merge such tests as it only increases the amount of code that needs to be maintained.

**Comment by hakuturu583** [comment]
> For example, I believe it is a good idea to check the protected field target_speed_ to verify the side effects of calling requestSpeedChange, or to check if the setOtherStatus method works correctly and verify if the protected field other_status_ is as expected. For that, I need a protected member accessor, which is implemented in the class we decided to provide.

I think these cases can be tested on `PedestrianEnttiy`/`VehicleEntity`/`MiscObjectEntity`

**Comment by robomic** [comment]
Due to major changes, this PR is being closed. See https://github.com/tier4/scenario_simulator_v2/pull/1286

**Pull request closed without merging**
