### PR TITLE
fix(launch): remove name keyword from nodes in launch file

### PR DESCRIPTION
**Pull request by lchojnack**
## Types of PR

- [ ] New Features
- [ ] Upgrade of existing features
- [x] Bugfix

## Link to the issue
https://tier4.atlassian.net/browse/RJD-728

## Description
This PR removes the `name` keyword for openscenario_interpeter, openscenario_prepreocessor, and simples_sensor_simulator nodes in launch file. 
The `name` keyword overrides the name for all created nodes, so duplicated nodes appear.

## How to review this PR.
1. launch `duplicated_node_checker` 
    ```ros2 launch duplicated_node_checker duplicated_node_checker.launch.xml```
2. check if duplicated nodes are detected
    ```ros2 topic echo /diagnostics | grep -A 12 -B 6 "Error: Duplicated nodes detected"```
3. launch ss2
    ```ros2 launch scenario_test_runner scenario_test_runner.launch.py scenario:='$(find-pkg-share scenario_test_runner)/scenario/ByValueCondition.UserDefinedValueCondition.yaml' vehicle_model:=lexus sensor_model:=aip_xx1 record:=false```
    
Before the fix, the duplicated nodes **are** detected on `/diagnostics` topic
After the fix, the duplicated nodes **are not** detected on `/diagnostics` topic

### CODE REVIEW

**Comment by HansRobo** [comment]
@lchojnack 
I think it is an unnatural change to use `launch_ros.actions.Node` instead of `launch_ros.actions.LifecycleNode` for `openscenario_interpreter_node`, which is a life-cycle node.
However, my **current** understanding is that this is because the behavior regarding the name argument of the `launch_ros.actions.LifecycleNode` constructor was inconvenient for this modification.

However, if we merge it as is, there is a possibility that developers who notice something strange (In the future, my memory will fade and I will become one of these developers) might change it back, so could you please comment out the details of this change in the source code?
(Since this is a comment change, no additional regression testing is required)

https://github.com/tier4/scenario_simulator_v2/pull/1126/files#diff-33c8f3e9ec566a585c9005a5b9b90b78452491dfed879f9a1590dd0f7a43922eR177

**Comment by HansRobo** [comment]
@lchojnack 
Thank you for adding information!
The all changes look good yo me.
I'll approve and merge this pull-request after finishing some internal tests I'm doing now.

**Comment by lchojnack** [comment]
@HansRobo 
Thank you for review. 
I've added the comment about the change from LifecycleNode to Node.

[Link to code](https://github.com/ros2/launch_ros/blob/humble/launch_ros/launch_ros/actions/lifecycle_node.py#L48C1-L74C12)  about the difference between LifecycleNode and Node

**Comment by HansRobo** [comment]
@lchojnack 
I found that some scenarios still have node duplicated error, as a result of internal test.
The error occurred when there were multiple `UserDefinedValueCondition` for the same topic as in the snippet below.

Could you fix for this error?
(I will provide internal test links in JIRA ticket)


## scenario snippet
```
ConditionGroup:
  - Condition:
      - name: ''
        delay: 0
        conditionEdge: none
        ByValueCondition:
          UserDefinedValueCondition:
            value: '0.5'
            name: >-
              /diagnostics_err_/autoware/control/autonomous_driving/performance_monitoring/trajectory_deviation/lane_departure_checker_nodetrajectory_deviation_lateraldeviation
            rule: greaterThan
  - Condition:
      - name: ''
        delay: 0
        conditionEdge: none
        ByValueCondition:
          UserDefinedValueCondition:
            value: '-0.5'
            name: >-
              /diagnostics_err_/autoware/control/autonomous_driving/performance_monitoring/trajectory_deviation/lane_departure_checker_nodetrajectory_deviation_lateraldeviation
            rule: lessThan
```

## Error (in `/diagnostics` topic)

```
{
  "header": {
    "stamp": {
      "sec": 1699518539,
      "nsec": 898556083
    },
    "frame_id": ""
  },
  "status": [
    {
      "level": 2,
      "name": "duplicated_node_checker: duplicated_node_checker",
      "message": "Error: Duplicated nodes detected",
      "hardware_id": "duplicated_node_checker",
      "values": [
        {
          "key": "Duplicated Node Name",
          "value": "/simulation/lane_departure_checker_nodetrajectory_deviation_lateraldeviation_subscription"
        }
      ]
    }
  ]
}
```

**Comment by lchojnack** [comment]
@HansRobo 

I've prepared the fix for the error. The fix is to add hash value based on name, rule, and value to the subscription node name. I think the hash should be unique enough to avoid duplicated nodes.

Duplicated nodes only can appears in the situation when there are exactly the same `UserDefinedValueCondition` as for example
```
- Condition:
    - name: ''
      delay: 0
      conditionEdge: none
      ByValueCondition:
        UserDefinedValueCondition:
          value: '0.5'
          name: >-
            /diagnostics_err_/autoware/control/autonomous_driving/performance_monitoring/trajectory_deviation/lane_departure_checker_nodetrajectory_deviation_lateraldeviation
          rule: greaterThan
- Condition:
    - name: ''
      delay: 0
      conditionEdge: none
      ByValueCondition:
        UserDefinedValueCondition:
          value: '0.5'
          name: >-
            /diagnostics_err_/autoware/control/autonomous_driving/performance_monitoring/trajectory_deviation/lane_departure_checker_nodetrajectory_deviation_lateraldeviation
          rule: greaterThan
```

Please let me know what you think about the fix

**Comment by lchojnack** [comment]
@HansRobo 
Yes, a static counter is the simplest solution. I've implemented the fix in that way.

Please let me know if the fix meets expectations. If yes, I will run the regression tests.

**Comment by HansRobo** [comment]
@lchojnack 
Thank you.
Your implementation looks good to me!
It's ok to run the regression test.

I also started to run test with NodeDeplicatedChecker-enabled autoware and scenarios which failed in previous test .
https://evaluation.tier4.jp/evaluation/reports/2ac0aba6-a60d-5311-a8c1-bfce67d61b7a?project_id=prd_jt

**Comment by HansRobo** [comment]
my tests are passed!

**Review by HansRobo — APPROVED** [review]
LGTM!
Thank you for the quick response

**Comment by HansRobo** [comment]
Oh, I forgot to add the release notes regarding this change.
I will add and merge.

**Pull request merged**
