### PR TITLE
Add traffic sim missing depend

### PR DESCRIPTION
**Pull request by adamkrawczyk**
## Types of PR

- [ ] Bugfix

## Description
Add quaternion_operation to package.xml and CMakeLists.txt to pass colcon build

### CODE REVIEW

**Comment by adamkrawczyk** [comment]
Issue rised at https://github.com/tier4/scenario_simulator_v2/issues/780

**Review by hakuturu583 — APPROVED** [review]
Thanks!

**Comment by hakuturu583** [comment]
Code looks good, but please pull upstream master branch.

**Review by hakuturu583 — CHANGES_REQUESTED** [review]
Code looks good, but please pull upstream master branch.

**Comment by adamkrawczyk** [comment]
@hakuturu583 
I have noticed double added `quaternion_operation` in `package.xml` --> caused rosdep to fall (I have only tested if build passes) sorry for this. Now there is only `CMakeLists.txt` file changed and at my setup, everything passes.

**Comment by hakuturu583** [comment]
Hummm...
I think your Generate Documentation actions seems old.
This problem was fixed in master branch.

**Comment by hakuturu583** [comment]
@adamkrawczyk friendly ping.

**Comment by adamkrawczyk** [comment]
@hakuturu583 than you for your ping -> I'm pinging you back ;)

**Review by hakuturu583 — APPROVED** [review]

**Pull request merged**
