### PR TITLE
Move traveled distance functionality to `traffic_simulator::API`

### PR DESCRIPTION
**Pull request by shouth**
## Types of PR

- [ ] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

## Description

`traffic_simulator` has the functionality to measure various metrics such as collision, standstill, travled distance and etc. These metrics implemetations are currently under replacement because most of them are trivial. This PR is to replace `TraveledDistanceMetrics` to `traffic_simulator::API::getTraveledDistance`.

## Others

This PR was originally worked on at #766, but it had a merge conflict with the master branch and I mistakenly discarded updates on feature/use_job_in_standstill_duration. So I open new PR to solve this problem while avoiding force push. If this PR is merged, #766 can be safely closed.

### CODE REVIEW

**Comment by hakuturu583** [comment]
Please follow upstream

**Review by hakuturu583 — CHANGES_REQUESTED** [review]
Please also update [release notes.](https://github.com/tier4/scenario_simulator_v2/blob/feature/start_npc_logic_api/docs/ReleaseNotes.md)

**Review by hakuturu583 — COMMENTED** [review]
LGTM 
I will check on my environment, please wait until it works right.

**Comment by shouth** [comment]
I managed to merge master into this branch. Since a lot of updates are introduced and original `getTraveledDistance` become old-fashioned, I adapt this function for these changes.

**Review by hakuturu583 — APPROVED** [review]

**Pull request merged**
