### PR TITLE
Feature/awf universe instruction

### PR DESCRIPTION
**Pull request by WJaworskiRobotec**
## Types of PR

- [X] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Description

Added instruction for running SS2 with Autoware Universe

## How to review this PR.

Test the instruction with scenario_runner and random_test_runner

### CODE REVIEW

**Comment by hakuturu583** [comment]
@WJaworskiRobotec I tested on your document but, I faced error with this log.

```
[simulation.concealer]: SetVelocityLimit service is not ready.
```
This log was seen in your local machine?

**Comment by WJaworskiRobotec** [comment]
@hakuturu583 in which step you notice this error ?

**Comment by hakuturu583** [comment]
> @hakuturu583 in which step you notice this error ?

I got the log when I execute this command.

```
ros2 launch scenario_test_runner scenario_test_runner.launch.py architecture_type:=awf/universe record:=false scenario:='$(find-pkg-share scenario_test_runner)/scenario/sample.yaml' sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle
```

**Comment by WJaworskiRobotec** [comment]
@hakuturu583 you are right. We tested the instruction around 1 week ago and it worked both for random testing and scenario testing. Let me check what has changed since then in both autoware and ss2 master branch and I will come back to you once it works again

**Comment by WJaworskiRobotec** [comment]
@hakuturu583 
the problem is caused by the change in this file on master branch :
https://github.com/tier4/scenario_simulator_v2/blame/master/openscenario/openscenario_interpreter/src/syntax/controller.cpp

with these change commented out everything works: 
```
  setVelocityLimit(
    entity_ref, properties.get<Double>("maxSpeed", std::numeric_limits<Double::value_type>::max()));
```
Should i try to fix it ? Obviously removing the code is not the solution :)

**Comment by hakuturu583** [comment]
@WJaworskiRobotec I try to run random test runner with awf universe.
But I faced error.
This is my local log.

```
ros2 launch random_test_runner random_test.launch.py architecture_type:=awf/universe sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle
[INFO] [launch]: All log files can be found below /home/masaya/.ros/log/2022-04-18-13-52-10-847621-dpc1808002-3857621
[INFO] [launch]: Default logging verbosity is set to INFO
Value of simulator_type: ['simple_sensor_simulator', 'unity']
Value of architecture_type: ['awf/auto', 'tier4/proposal']
Test param file 
Autoware architecture awf/universe
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=KeyError('awf/universe')>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/home/masaya/workspace/autoware/install/random_test_runner/share/random_test_runner/launch/random_test.launch.py", line 159, in launch_setup
    {"autoware_launch_package": default_autoware_launch_package_of(autoware_architecture),
  File "/home/masaya/workspace/autoware/install/random_test_runner/share/random_test_runner/launch/random_test.launch.py", line 36, in default_autoware_launch_package_of
    return {
KeyError: 'awf/universe'
```

**Comment by WJaworskiRobotec** [comment]
@hakuturu583 have you checked out this [PR](https://github.com/tier4/scenario_simulator_v2/pull/697/) on top of your master branch ? Error looks like you don't have the changes in random test runner supporting awf/universe

**Comment by hakuturu583** [comment]
@WJaworskiRobotec Yes, I tested your documentation under master branch.

**Comment by hakuturu583** [comment]
@WJaworskiRobotec Can you this problem in master branch?

**Comment by WJaworskiRobotec** [comment]
Let me test it once again, Did it work for you on master branch for scenario_test_runner ? I would not expect random_test_runner to work without merging the PR that i mentioned above

**Review by hakuturu583 — APPROVED** [review]

**Comment by hakuturu583** [comment]
@WJaworskiRobotec Thanks! it works.

**Pull request merged**
