### PR TITLE
feat(parameters_visualization): visualize test iteration parameters

### PR DESCRIPTION
**Pull request by ahmeddesokyebrahim**
# Description
fixes https://github.com/tier4/scenario_simulator_v2/issues/1272

## Abstract

This PR is to add the ability for scenario simulator to report the parameters used in each iteration as described in this [feature request](https://github.com/tier4/scenario_simulator_v2/issues/1272).
The PR is adding this parameters reporting using both command line print and rviz plugin visualization that can enabled when needed

## Background
Please refer to the [feature request](https://github.com/tier4/scenario_simulator_v2/issues/1272).

## Details
Using this PR, the parameters are printed to command line and visualized in RVIZ as follows : 
- RVIZ :
image
- Terminal :
image

## References
N.A

# Destructive Changes
N.A 

# Known Limitations

### CODE REVIEW

**Comment by hakuturu583** [comment]
@ahmeddesokyebrahim Why the base branch of this pull request is not master branch?
I reviewed your diff but it is not depends on master.

**Comment by ahmeddesokyebrahim** [comment]
> Why the base branch of this pull request is not master branch? I reviewed your diff but it is not depends on autoware_msgs branch.

Thanks @hakuturu583 -san for your reply.
As was under impression that this is the branch used due to this change [here](https://github.com/autowarefoundation/autoware/blob/main/simulator.repos).

So, the needed fix now is to have the target or base branch for the PR to be master. Is it correct ?

**Comment by ahmeddesokyebrahim** [comment]
Hi @hakuturu583 -san,

Is this [PR](https://github.com/tier4/scenario_simulator_v2/pull/1360) set up as needed ?

If yes, I can close this one and consider the new PR.

**Comment by hakuturu583** [comment]
> So, the needed fix now is to have the target or base branch for the PR to be master. Is it correct ?

Yes. I think this base branch of this pull request should be master.
I checked diff but it seems this pull request does not depends on autoware_msgs

**Comment by hakuturu583** [comment]
> Hi @hakuturu583 -san,
  Is this https://github.com/tier4/scenario_simulator_v2/pull/1360 set up as needed ?
  If yes, I can close this one and consider the new PR.

I think this is very helpful feature.
Could you re-open pull request based on master branch?

**Comment by ahmeddesokyebrahim** [comment]
> I think this is very helpful feature.
> Could you re-open pull request based on master branch?

Thanks for your comment @hakuturu583 -san 
Can you please check this PR https://github.com/tier4/scenario_simulator_v2/pull/1360 ?

**Comment by hakuturu583** [comment]
@ahmeddesokyebrahim Thanks!
I will check!

**Comment by hakuturu583** [comment]
@ahmeddesokyebrahim Thak you for re-opening new pull request.
Can I close this pull request?

**Comment by ahmeddesokyebrahim** [comment]
> @ahmeddesokyebrahim Thak you for re-opening new pull request. Can I close this pull request?

Thanks for your comment @hakuturu583 -san.

I close this PR with this comment and we consider the other [PR](https://github.com/tier4/scenario_simulator_v2/pull/1360) based on master branch.

Thanks again.

**Pull request closed without merging**
